apiVersion: apps/v1
kind: Deployment
metadata:
  name: udapeople
  labels:
    app: udapeople
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udapeople
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udapeople
    spec:
      containers:
        - image: robinhalfbloodprince/udapeople
          imagePullPolicy: Always
          name: udapeople
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          ports:
            - containerPort: 5000

